### ISSUE TITLE
Remove tabulated gravity and cross-section file names from config dictionary

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/hydrad_tools#50]
Currently there are separate options for `tabulated_gravity_profile` and `tabulated_gravity_file`. If `tabulated_gravity_profile` exists, `tabulated_gravity_file` is added to the config dictionary. There really is no need for this as the tabulated gravity filename is hardcoded anyway. In the template, there should just be a check for the existence of the `tabulated_gravity_profile` key and it is there, use the hardcoded `tabulated.gravity` filename.

All of this applies to the variable cross-section as well.

**Comment by sjbradshaw** [comment]
The tabulated_gravity (and tabulated_cross_section) pre-processor directives in HYDRAD are now defunct and replaced with USE_POLY_FIT_TO_GRAVITY and USE_POLY_FIT_TO_MAGNETIC_FIELD; this is because tabulated values are no longer used for either of these quantities. Instead, polynomial (6th order) fits are made and evaluated to find g(s) and B(s).
