### ISSUE TITLE
Cannot configure beam heating

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/hydrad_tools#69]
There is currently no way to configure beam heating profiles. I'm not sure if this is a separate file or can be folded into `heating.cfg` somehow. If this is a separate file, what is the format and what are the necessary inputs?

ping @jwreep

**Comment by jwreep** [comment]
It's a separate file.  The inputs are the number of entries (first line), and then for each entry the start time, energy flux, low energy cut-off, and spectra index.  Each variable is interpolated between entries.

One example:

3     
Time    Energy_flux     Cut-off Spectral_index      
[s]        [erg/cm^2/s]   [keV]     
0.0       0E10                 15.0        5.0      
50.0     3.1623E10       15.0         5.0     
100.0   0E10                 15.0        5.0     


This creates a beam with constant cut-off 15 keV and spectral index 5, that varies in a triangular profile up to 10^10.5 erg/s/cm^2, lasting a total of 100 s.

If only one entry is specified, the time column specifies duration, rather than start time.

**Comment by wtbarnes** [comment]
It is assumed that this file lives at `Heating_Model/config/beam_heating_model.cfg`
